CREATE TABLE [dbo].[Customer] (
    [IDCustomer]        INT              IDENTITY (1, 1) NOT NULL,
    [IDCustomerParent]  INT              NULL,
    [IDCity]            INT              NULL,
    [Name]              VARCHAR (300)    NOT NULL,
    [CRECI]             VARCHAR (20)     NULL,
    [CPF_CNPJ]          VARCHAR (20)     NULL,
    [Address]           VARCHAR (250)    NOT NULL,
    [PostalCode]        VARCHAR (10)     NULL,
    [Phone1]            VARCHAR (20)     NOT NULL,
    [Phone2]            VARCHAR (20)     NULL,
    [CellPhone]         VARCHAR (20)     NULL,
    [Logo]              VARCHAR (300)    NULL,
    [AddressNumber]     NVARCHAR (15)    NULL,
    [AddressComplement] NVARCHAR (50)    NULL,
    [UserName]          VARCHAR (200)    NULL,
    [SiteName]          VARCHAR (200)    NULL,
    [Comments]          TEXT             NULL,
    [DetailView]        BIGINT           NULL,
    [ActivateKey]       UNIQUEIDENTIFIER NULL,
    [IsPromoted]        BIT              NULL,
    [Status]            SMALLINT         NULL,
    [CreateDate]        DATETIME         NULL,
    [ModifyDate]        DATETIME         NULL,
    [CreatedBy]         VARCHAR (50)     NULL,
    [ModifiedBy]        VARCHAR (50)     NULL,
    [NotifyBy]          SMALLINT         NULL,
    [Email]             NVARCHAR (200)   NOT NULL,
    [IDStateProvince]   INT              NULL,
    [IDCountry]         VARCHAR (5)      NULL,
    [SkypeName]         NVARCHAR (200)   NULL,
    [Facebook]          NVARCHAR (200)   NULL,
    [Twitter]           NVARCHAR (200)   NULL,
    [Pinterest]         NVARCHAR (200)   NULL,
    [Linkedin]          NVARCHAR (200)   NULL,
    [ExternalSiteID]    NVARCHAR (200)   NULL,
    [AllowShowAddress]  BIT              NULL,
    CONSTRAINT [PK__Customer__023D5A04] PRIMARY KEY CLUSTERED ([IDCustomer] ASC),
    CONSTRAINT [FK_Customer_City] FOREIGN KEY ([IDCity]) REFERENCES [dbo].[City] ([IDCity]),
    CONSTRAINT [FK_Customer_Customer] FOREIGN KEY ([IDCustomerParent]) REFERENCES [dbo].[Customer] ([IDCustomer])
);

