CREATE TABLE [dbo].[Element] (
    [IDElement]                  BIGINT          IDENTITY (1, 1) NOT NULL,
    [IDHierarchyStructure]       INT             NOT NULL,
    [IDHierarchyStructureParent] INT             NOT NULL,
    [IDPurpose]                  INT             DEFAULT ((1)) NOT NULL,
    [IDCity]                     INT             NULL,
    [IDCustomer]                 INT             NOT NULL,
    [IDItemSite]                 VARCHAR (25)    NULL,
    [Latitude]                   DECIMAL (11, 8) NOT NULL,
    [Longitude]                  DECIMAL (11, 8) NOT NULL,
    [ShowAddress]                BIT             DEFAULT ((1)) NOT NULL,
    [Address]                    NVARCHAR (1000) NOT NULL,
    [PageView]                   BIGINT          DEFAULT ((0)) NULL,
    [DetailView]                 BIGINT          DEFAULT ((0)) NULL,
    [IsPromoted]                 BIT             NULL,
    [Url]                        VARCHAR (300)   NULL,
    [Status]                     SMALLINT        NOT NULL,
    [ModifyDate]                 DATETIME        NULL,
    [CreateDate]                 DATETIME        DEFAULT (getdate()) NULL,
    [CreatedBy]                  VARCHAR (50)    NULL,
    [ModifiedBy]                 VARCHAR (50)    NULL,
    [Acronym]                    VARCHAR (4)     NULL,
    [Discriminator]              NVARCHAR (127)  DEFAULT ('X') NULL,
    [AllowRatting]               BIT             NULL,
    [Neighborhood]               NVARCHAR (500)  NULL,
    [DefaultPicturePath]         NVARCHAR (500)  NULL,
    CONSTRAINT [PK_Element] PRIMARY KEY CLUSTERED ([IDElement] ASC, [IDHierarchyStructure] ASC, [IDHierarchyStructureParent] ASC),
    CONSTRAINT [FK_Element_City] FOREIGN KEY ([IDCity]) REFERENCES [dbo].[City] ([IDCity]),
    CONSTRAINT [FK_Element_Customer] FOREIGN KEY ([IDCustomer]) REFERENCES [dbo].[Customer] ([IDCustomer]),
    CONSTRAINT [FK_Element_HierarchyStructure] FOREIGN KEY ([IDHierarchyStructureParent]) REFERENCES [dbo].[HierarchyStructure] ([IDHierarchyStructure]),
    CONSTRAINT [FK_Element_Purpose] FOREIGN KEY ([IDPurpose]) REFERENCES [dbo].[Purpose] ([IDPurpose])
);

