//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpongeSolutions.ServicoDireto.Internationalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Enum {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enum() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpongeSolutions.ServicoDireto.Internationalization.Enum", typeof(Enum).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string ChoiceType_No {
            get {
                return ResourceManager.GetString("ChoiceType_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string ChoiceType_Yes {
            get {
                return ResourceManager.GetString("ChoiceType_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatePicker.
        /// </summary>
        public static string ComponentType_DatePicker {
            get {
                return ResourceManager.GetString("ComponentType_DatePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range Slider.
        /// </summary>
        public static string ComponentType_RangeSlider {
            get {
                return ResourceManager.GetString("ComponentType_RangeSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBox.
        /// </summary>
        public static string ComponentType_TextBox {
            get {
                return ResourceManager.GetString("ComponentType_TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluído.
        /// </summary>
        public static string EmailType_Excluded {
            get {
                return ResourceManager.GetString("EmailType_Excluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Email.
        /// </summary>
        public static string EmailType_NewEmail {
            get {
                return ResourceManager.GetString("EmailType_NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lido.
        /// </summary>
        public static string EmailType_Read {
            get {
                return ResourceManager.GetString("EmailType_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviado.
        /// </summary>
        public static string EmailType_Sent {
            get {
                return ResourceManager.GetString("EmailType_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ.
        /// </summary>
        public static string FederealIDType_CNPJ {
            get {
                return ResourceManager.GetString("FederealIDType_CNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        public static string FederealIDType_CPF {
            get {
                return ResourceManager.GetString("FederealIDType_CPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        public static string HierarchyItemType_Category {
            get {
                return ResourceManager.GetString("HierarchyItemType_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string HierarchyItemType_Type {
            get {
                return ResourceManager.GetString("HierarchyItemType_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por e-Mail.
        /// </summary>
        public static string NotifyType_Email {
            get {
                return ResourceManager.GetString("NotifyType_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por SMS.
        /// </summary>
        public static string NotifyType_SMS {
            get {
                return ResourceManager.GetString("NotifyType_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        public static string StatusType_Active {
            get {
                return ResourceManager.GetString("StatusType_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inativo.
        /// </summary>
        public static string StatusType_Inactive {
            get {
                return ResourceManager.GetString("StatusType_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendente.
        /// </summary>
        public static string StatusType_Pending {
            get {
                return ResourceManager.GetString("StatusType_Pending", resourceCulture);
            }
        }
    }
}
