//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpongeSolutions.ServicoDireto.Internationalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpongeSolutions.ServicoDireto.Internationalization.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Account_Logon_Login_Unsuccessful {
            get {
                return ResourceManager.GetString("Account_Logon_Login_Unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos as fotos foram enviadas com sucesso..
        /// </summary>
        public static string All_Files_Were_Uploaded_Sucessfully {
            get {
                return ResourceManager.GetString("All_Files_Were_Uploaded_Sucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atributos não foram encontrados..
        /// </summary>
        public static string Attributes_Not_Found {
            get {
                return ResourceManager.GetString("Attributes_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionado aos favoritos.
        /// </summary>
        public static string Bookmark_Added {
            get {
                return ResourceManager.GetString("Bookmark_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removido dos favoritos.
        /// </summary>
        public static string Bookmark_Removed {
            get {
                return ResourceManager.GetString("Bookmark_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha outro nome de usuário.
        /// </summary>
        public static string Choose_Another_Username {
            get {
                return ResourceManager.GetString("Choose_Another_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma a desativação?.
        /// </summary>
        public static string Confirm_Deactivation {
            get {
                return ResourceManager.GetString("Confirm_Deactivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma a deleção?.
        /// </summary>
        public static string Confirm_Deletion {
            get {
                return ResourceManager.GetString("Confirm_Deletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente não encontrado.
        /// </summary>
        public static string Customer_Not_Found {
            get {
                return ResourceManager.GetString("Customer_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem principal definida com sucesso!.
        /// </summary>
        public static string Default_Image_Defined {
            get {
                return ResourceManager.GetString("Default_Image_Defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um usuário vinculado a este e-mail informado.
        /// </summary>
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome de usuário existente, por favor informe outro..
        /// </summary>
        public static string DuplicateUserName {
            get {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imóvel adicionado como favorito.
        /// </summary>
        public static string Element_Added_As_Favourite {
            get {
                return ResourceManager.GetString("Element_Added_As_Favourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imóvel não pertence ao usuário autenticado..
        /// </summary>
        public static string Element_Does_Not_Belongs_To_Customer {
            get {
                return ResourceManager.GetString("Element_Does_Not_Belongs_To_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imóvel inserido com sucesso.
        /// </summary>
        public static string Element_Inserted_Successfully {
            get {
                return ResourceManager.GetString("Element_Inserted_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imóvel não encontrado.
        /// </summary>
        public static string Element_Not_Found {
            get {
                return ResourceManager.GetString("Element_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imóvel removido dos favoritos.
        /// </summary>
        public static string Element_Removed_As_Favourite {
            get {
                return ResourceManager.GetString("Element_Removed_As_Favourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imóvel atualizado com sucesso.
        /// </summary>
        public static string Element_Updated_Successfully {
            get {
                return ResourceManager.GetString("Element_Updated_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email não foi informado.
        /// </summary>
        public static string Email_Empty {
            get {
                return ResourceManager.GetString("Email_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail foi enviado com sucesso..
        /// </summary>
        public static string Email_Has_Been_Sent_Successfully {
            get {
                return ResourceManager.GetString("Email_Has_Been_Sent_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ou Usuário não foram informados..
        /// </summary>
        public static string Email_or_UserName_Empty {
            get {
                return ResourceManager.GetString("Email_or_UserName_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your e-mail.
        ///If the e-mail address you entered is associated with a customer account in our records, you will receive an e-mail from us with instructions for resetting your password. If you don&apos;t receive this e-mail, please check your junk mail folder or visit our Help pages to contact Customer Service for further assistance..
        /// </summary>
        public static string Email_Password_Recover_Sent {
            get {
                return ResourceManager.GetString("Email_Password_Recover_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail enviado com sucesso.
        /// </summary>
        public static string Email_Sent_Successfully {
            get {
                return ResourceManager.GetString("Email_Sent_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro!!! Contate o administrador.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao desativar.
        /// </summary>
        public static string Error_Deactivation {
            get {
                return ResourceManager.GetString("Error_Deactivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação de senha não está correta.
        /// </summary>
        public static string General_PasswordMatches {
            get {
                return ResourceManager.GetString("General_PasswordMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem excluída com sucesso.
        /// </summary>
        public static string Image_Deleted_Successfully {
            get {
                return ResourceManager.GetString("Image_Deleted_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagens excluídas com sucesso.
        /// </summary>
        public static string Images_Deleted_Successfully {
            get {
                return ResourceManager.GetString("Images_Deleted_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados inválidos de autenticação!.
        /// </summary>
        public static string Invalid_Authentication {
            get {
                return ResourceManager.GetString("Invalid_Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password retrieval answer provided is invalid. Please check the value and try again..
        /// </summary>
        public static string InvalidAnswer {
            get {
                return ResourceManager.GetString("InvalidAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail informado é inválido, por favor informe outro..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha informada é inválida, por favor informe novamente. Para tornar sua senha mais segura e válida, use letras maiúsculas e minúsculas, números e caracteres especiais, como @, % e !..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password retrieval question provided is invalid. Please check the value and try again..
        /// </summary>
        public static string InvalidQuestion {
            get {
                return ResourceManager.GetString("InvalidQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome de usuário informado é inválido, por favor informe outro..
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de imagens excedeu o permitido [{0}].
        /// </summary>
        public static string Number_Of_Images_Exceeded_Allowed {
            get {
                return ResourceManager.GetString("Number_Of_Images_Exceeded_Allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha alterada com sucesso.
        /// </summary>
        public static string Password_Changed_Successfully {
            get {
                return ResourceManager.GetString("Password_Changed_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha Incorreta.
        /// </summary>
        public static string Password_Incorrect {
            get {
                return ResourceManager.GetString("Password_Incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha Inválida.
        /// </summary>
        public static string Password_Invalid {
            get {
                return ResourceManager.GetString("Password_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem do perfil alterada com sucesso.
        /// </summary>
        public static string Profile_Image_Changed {
            get {
                return ResourceManager.GetString("Profile_Image_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication provider returned an error. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string ProviderError {
            get {
                return ResourceManager.GetString("ProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro deletado com sucesso.
        /// </summary>
        public static string Record_Deleted_Successfully {
            get {
                return ResourceManager.GetString("Record_Deleted_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro Inserido com Sucesso.
        /// </summary>
        public static string Record_Inserted_Successfully {
            get {
                return ResourceManager.GetString("Record_Inserted_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro não encontrado.
        /// </summary>
        public static string Record_Not_Found {
            get {
                return ResourceManager.GetString("Record_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro Atualizado com Sucesso.
        /// </summary>
        public static string Record_Updated_Successfully {
            get {
                return ResourceManager.GetString("Record_Updated_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione os itens a serem excluídos..
        /// </summary>
        public static string Select_Items_To_Be_Deleted {
            get {
                return ResourceManager.GetString("Select_Items_To_Be_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome de site já existente, tente outro..
        /// </summary>
        public static string SiteName_Already_Exists {
            get {
                return ResourceManager.GetString("SiteName_Already_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred. Please verify your entry and try again. If the problem persists, please contact your system administrator.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de media enviada não possui suporte..
        /// </summary>
        public static string Unsuported_MediaType {
            get {
                return ResourceManager.GetString("Unsuported_MediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário inserido com sucesso.
        /// </summary>
        public static string User_Inserted_Successfully {
            get {
                return ResourceManager.GetString("User_Inserted_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não autenticado.
        /// </summary>
        public static string User_Not_Authenticated {
            get {
                return ResourceManager.GetString("User_Not_Authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado.
        /// </summary>
        public static string User_Not_Found {
            get {
                return ResourceManager.GetString("User_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de ativação enviado, aguardando confirmação de usuário..
        /// </summary>
        public static string User_Register_Code_Has_Been_Sent {
            get {
                return ResourceManager.GetString("User_Register_Code_Has_Been_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário atualizado com sucesso.
        /// </summary>
        public static string User_Updated_Successfully {
            get {
                return ResourceManager.GetString("User_Updated_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user creation request has been canceled. Please verify your entry and try again. If the problem persists, please contact your system administrator.
        /// </summary>
        public static string UserRejected {
            get {
                return ResourceManager.GetString("UserRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem campos que não foram preenchidos..
        /// </summary>
        public static string ValidationSummary {
            get {
                return ResourceManager.GetString("ValidationSummary", resourceCulture);
            }
        }
    }
}
